endlessm/gnome-initial-setup

- gnome-initial-setup/gis-driver.c
- gnome-initial-setup/gis-driver.h
- gnome-initial-setup/pages/summary/gis-summary-page.c
> Shell: Start tutorial on all user's first login

- gnome-initial-setup/pages/account/gis-account-page.c
> FBE: Fixed password and confirmation matching logic

- gnome-initial-setup/pages/summary/com.endlessm.Tutorial.FBERemote.xml
- gnome-initial-setup/pages/summary/gis-summary-page.c
> summary: forward current user language to the tutorial

- gnome-initial-setup/pages/account/gis-account-page.c
- gnome-initial-setup/pages/account/gis-account-page.ui
When creating the user account, offers the user a way to hint what is the
password, in case they don't remind it later.
[endlessm/eos-shell#1623]
> Add password reminder

- gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.ui
> Add focus to Metrics button

- gnome-initial-setup/pages/language/gis-language-page.c
Now tested and working.
[endlessm/eos-shell#5036]
> Factory test mode fixes

- gnome-initial-setup/pages/location/cc-timezone-monitor.c
This avoids a race condition that can happen when the callback is
executed after this page has been disposed. Probably related to a memory
leak in GLib: https://git.gnome.org/browse/glib/commit/?id=dafc454e
[endlessm/eos-shell#5438]
> timezone-monitor: disconnect callback from location-changed on finalize

- gnome-initial-setup/pages/display/gis-display-page.c
https://phabricator.endlessm.com/T11995
> display: use common heuristic to determine if overscan is supported

- po/POTFILES.in
https://phabricator.endlessm.com/T12547
> Add new files to POTFILES.in

- debian/control
https://phabricator.endlessm.com/T12548
> T12548: depend on eos-installer

- gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.c
- gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.ui
This is the `master` counterpart of
https://github.com/endlessm/gnome-initial-setup/pull/140
https://phabricator.endlessm.com/T13890
> eula: disable metrics on live systems

- gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.c
https://phabricator.endlessm.com/T15370
> live-chooser: fix path to Chrome system helper

- gnome-initial-setup/gis-pkexec.c
- gnome-initial-setup/gis-pkexec.h
- gnome-initial-setup/pages/language/gis-language-page.c
- gnome-initial-setup/pages/live-chooser/eos-setup-live-user
- gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.c
https://phabricator.endlessm.com/T15370
https://phabricator.endlessm.com/T15438
> live: don't clobber image-specific icon grid; restore Chromium

- debian/rules
https://phabricator.endlessm.com/T15834
> Specify location for our vendor overrides

- gnome-initial-setup/pages/branding-welcome/gis-branding-welcome-page.c
- gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.c
The group is called "Welcome", not "Info".
https://phabricator.endlessm.com/T15834
> branding: fix copy/paste typo

- po/id.po
This is not a simple cherry-pick because, in master:
* Many English strings have had ASCII quotes " replaced with curly
quotes “
* The first few screens have been refactored so many string location
comments have changed
This patch manually merges these string changes.
https://phabricator.endlessm.com/T16485
> Backport updated Indonesian translations

- gnome-initial-setup/pages/language/eos-test-mode
https://phabricator.endlessm.com/T16836
> test-mode: Disable eos-phone-home

- gnome-initial-setup/pages/live-chooser/eos-setup-live-user
https://phabricator.endlessm.com/T15704
> move eos-image-defaults to /var/lib

- gnome-initial-setup/pages/timezone/gis-timezone-page.c
Instead of always using 24h. This code will become simpler once we have
a newer version of GLib, where GDateTime always supports formatting
AM/PM time.
https://phabricator.endlessm.com/T17468
> timezone: set default 12h/24h from locale

- gnome-initial-setup/pages/goa/gis-goa-page.c
https://phabricator.endlessm.com/T17486
> goa: reorder accounts

- gnome-initial-setup/gis-assistant.c
- gnome-initial-setup/gis-driver.c
- gnome-initial-setup/gis-page.c
- gnome-initial-setup/pages/goa/gis-goa-page.c
- gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.c
- gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.ui
- gnome-initial-setup/pages/password/gis-password-page.c
- gnome-initial-setup/pages/summary/gis-summary-page.c
- gnome-initial-setup/pages/summary/gis-summary-page.ui
https://phabricator.endlessm.com/T17622
> Fix live-chooser page

- gnome-initial-setup/pages/account/gis-account-page-local.c
https://phabricator.endlessm.com/T843
> account-local: set sunflower as default avatar image

- gnome-initial-setup/pages/language/cc-common-language.c
These languages are where we invest in translations/apps most actively, sorted
roughly by volume.
https://phabricator.endlessm.com/T18020
> change top 8 languges in chooser to match Endless target markets

- gnome-initial-setup/pages/timezone/gis-timezone-page.c
It is not intuitive that users have to explicitly search to set a
location when clicking on a map should work just as well. In that case,
use the nearest city from the latitude/longitude reported by the
TzLocation object.
https://phabricator.endlessm.com/T18040
> timezone: set location when clicking on map

- gnome-initial-setup/gis-page-util.c
This is a follow up for https://phabricator.endlessm.com/T18734
> demo mode: hook up cancel button to hide the dialog

- debian/control
- debian/control.in
https://phabricator.endlessm.com/T18708
> Add libudisks2 dependency

- gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.c
https://phabricator.endlessm.com/T19000
> endless: Don't show EULA in demo mode

- gnome-initial-setup/gis-page-util.ui
https://phabricator.endlessm.com/T18996
> Demo mode: update phrasing of the dialog message

- gnome-initial-setup/gis-assistant.c
- gnome-initial-setup/gis-driver.c
- gnome-initial-setup/pages/language/gis-language-page.c
https://phabricator.endlessm.com/T18995
> T18995: Indicate visually that we are in demo mode

- gnome-initial-setup/gis-page-util.c
https://phabricator.endlessm.com/T19032
> page-util: don't enter demo mode for live sessions

- gnome-initial-setup/pages/language/gis-language-page.c
- gnome-initial-setup/pages/language/gis-language-page.ui
https://phabricator.endlessm.com/T18984
> Language page: hide enter-store-demo button when in demo mode

- gnome-initial-setup/pages/language/gis-language-page.ui
Or it will change color after the first click...
https://phabricator.endlessm.com/T19100
> language: don't track visited links for demo mode label

- data/Makefile.am
- data/com.endlessm.DemoMode.rules
- gnome-initial-setup/pages/language/eos-test-mode
https://phabricator.endlessm.com/T18999
> Demo mode: add support to install/uninstall flatpaks

- gnome-initial-setup/gis-driver.c
- gnome-initial-setup/gnome-initial-setup.h
- gnome-initial-setup/pages/account/gis-account-page-local.c
Use the same default avatar (the sunflower)
as for any other EOS user.
https://phabricator.endlessm.com/T19144
> Demo mode: use as well the default avatar

- gnome-initial-setup/pages/password/gis-password-page.c
- gnome-initial-setup/pages/password/gis-password-page.ui
This reverts commit deef21c0a7175a1435f2ef5b65da9a5b3acaf4eb.
https://phabricator.endlessm.com/T18591
> Revert "password: Enable Show Password by default"

- gnome-initial-setup/pages/password/gis-password-page.c
If the current keyboard layout is not a latin one we will add the fallback kbd layout 'en'. This calls out to gnome-shell where the logic to detect the keyboard layout is kept. The layout will be available in the popup switcher and the taskbar keyboard layout switcher.
https://phabricator.endlessm.com/T18598
> passwordPage: make latin kbd layout (en) available for password entries

- gnome-initial-setup/pages/display/Makefile.am
- gnome-initial-setup/pages/display/cc-display-config-dbus.c
- gnome-initial-setup/pages/display/cc-display-config-dbus.h
- gnome-initial-setup/pages/display/cc-display-config-manager-dbus.c
- gnome-initial-setup/pages/display/cc-display-config-manager-dbus.h
- gnome-initial-setup/pages/display/cc-display-config-manager.c
- gnome-initial-setup/pages/display/cc-display-config-manager.h
- gnome-initial-setup/pages/display/cc-display-config.c
- gnome-initial-setup/pages/display/cc-display-config.h
- gnome-initial-setup/pages/display/gis-display-page.c
https://phabricator.endlessm.com/T21591
> Reimplement the Display page using org.gnome.Mutter.DisplayConfig

- gnome-initial-setup/pages/password/gis-password-page.c
https://phabricator.endlessm.com/T22042
> Don't use a previously introduced password for non protected accounts

- configure.ac
- gnome-initial-setup/Makefile.am
- gnome-initial-setup/gnome-initial-setup.c
- gnome-initial-setup/pages/Makefile.am
- gnome-initial-setup/pages/site/Makefile.am
- gnome-initial-setup/pages/site/README.md
- gnome-initial-setup/pages/site/deployment-sites.json.example
- gnome-initial-setup/pages/site/eos-write-location
- gnome-initial-setup/pages/site/gis-site-page.c
- gnome-initial-setup/pages/site/gis-site-page.h
- gnome-initial-setup/pages/site/gis-site-page.ui
- gnome-initial-setup/pages/site/gis-site-search-entry.c
- gnome-initial-setup/pages/site/gis-site-search-entry.h
- gnome-initial-setup/pages/site/gis-site.c
- gnome-initial-setup/pages/site/gis-site.h
- gnome-initial-setup/pages/site/site.gresource.xml
- po/POTFILES.in
These details will be included in metrics messages.
See README.md file for more details.
https://phabricator.endlessm.com/T18842
> site: add page to track site-specific details for deployments

- gnome-initial-setup/pages/site/gis-site-page.c
This is a requirement for Conafe.
> site: allow manual editing of the ID field

- debian/changelog
https://phabricator.endlessm.com/T23346
> New version rebased on gnome-3-28

- gnome-initial-setup/pages/summary/gis-summary-page.c
On hack images, upon the completion of the FBE, we want to launch our
"HackUnlock" puzzle application. We use Clippy to connect to the state
notification for its unlocked state; when that is received we can
proceed with the login as usual.
Note that due to a race condition in when Clippy exports its
interface, we need to add a timeout before calling the Connect()
method. This is possible to fix with a different Clippy/GTK
integration, or a different Clippy API, but for now the timeout at
least allows us to move forward without blocking on that.
https://phabricator.endlessm.com/T23942
> summary: add support to launch initial contact app on Hack images

- gnome-initial-setup/pages/account/um-photo-dialog.c
- gnome-initial-setup/pages/language/cc-common-language.c
- meson.build
- meson_options.txt
Instead of a custom build option.
https://phabricator.endlessm.com/T23766
> account: use vendor file for alternative faces directory

- data/initial-setup.json
We depend on that component to display quest dialogs.
https://phabricator.endlessm.com/T24279
> Add clubhouse component to initial-setup session mode

- gnome-initial-setup/pages/account/gis-account-page-local.c
- gnome-initial-setup/pages/account/um-photo-dialog.c
This will allow images to customize the default avatar.
https://phabricator.endlessm.com/T24421
> account: allow to specify a different avatar from vendor conf

- gnome-initial-setup/gis-driver.c
- gnome-initial-setup/pages/summary/gis-summary-page.c
https://phabricator.endlessm.com/T24453
> driver: Emit sound on startup

- gnome-initial-setup/pages/account/gis-account-page-local.c
This page will be redesigned in the next rebase, but this is a
high-visibility fix that is at the same time very simple.
https://phabricator.endlessm.com/T24488
> account: don't dim avatar image preview

- gnome-initial-setup/gis-driver.c
- gnome-initial-setup/gis-driver.h
- gnome-initial-setup/gis-page-util.c
- gnome-initial-setup/gis-page-util.h
- gnome-initial-setup/pages/account/account.gresource.xml
- gnome-initial-setup/pages/account/gis-account-page-eula-dialog.c
- gnome-initial-setup/pages/account/gis-account-page-eula-dialog.h
- gnome-initial-setup/pages/account/gis-account-page-eula-dialog.ui
- gnome-initial-setup/pages/account/gis-account-page-local.c
- gnome-initial-setup/pages/account/gis-account-page-local.ui
- gnome-initial-setup/pages/account/gis-account-page.c
- gnome-initial-setup/pages/account/gis-account-page.ui
- gnome-initial-setup/pages/account/meson.build
- gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.c
- gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.ui
- gnome-initial-setup/pages/endless-eula/gis-endless-eula-viewer.c
- gnome-initial-setup/pages/endless-eula/gis-endless-eula-viewer.h
- gnome-initial-setup/pages/endless-eula/meson.build
https://phabricator.endlessm.com/T23646
> T23646 eula

- gnome-initial-setup/pages/summary/gis-summary-page.c
https://phabricator.endlessm.com/T24631
> summary: Launch HackUnlock asynchronously

- gnome-initial-setup/pages/account/gis-account-page-local.c
https://phabricator.endlessm.com/T25008
> account: Enable automatic login on Hack

- gnome-initial-setup/pages/account/gis-account-page-local.c
https://phabricator.endlessm.com/T25106
> account: Don't create shared user for Hack

- data/product_serial.conf
This will allow us to use the product_serial for the account creation.
https://phabricator.endlessm.com/T25480
> Add product_serial file to the tmpfile.d

- gnome-initial-setup/pages/account/um-photo-dialog.c
This patch uses the gnome-control-center user-accounts facesdir
configuration to override the default faces dir.
https://phabricator.endlessm.com/T27788
> account: Use control-center setting to override faces

- gnome-initial-setup/gis-driver.c
- gnome-initial-setup/gis-driver.h
- gnome-initial-setup/pages/account/gis-account-pages.c
- gnome-initial-setup/pages/goa/gis-goa-page.c
- gnome-initial-setup/pages/password/gis-password-page.c
- gnome-initial-setup/pages/site/gis-site-page.c
- gnome-initial-setup/pages/summary/gis-summary-page.c
- gnome-initial-setup/pages/timezone/gis-timezone-page.c
https://phabricator.endlessm.com/T27772
> Adjust live boot UI for persistent data storage feature

- po/ar.po
- po/fr.po
- po/hi.po
- po/id.po
- po/zh_TW.po
I have fixed the broken strings.
https://phabricator.endlessm.com/T27764
> Updates from Transifex

- NEWS
- data/gnome-initial-setup-copy-worker.service.in
- data/gnome-initial-setup-first-login.service.in
- gnome-initial-setup/gis-driver.c
- meson.build
- po/ca.po
- po/ja.po
Minor conflicts in po/ca.po and po/ja.po. Only one change that we didn't
already have downstream.
https://phabricator.endlessm.com/T28175
> Update to 3.34.1

- debian/changelog
Nothing interesting here.
https://phabricator.endlessm.com/T28175
> Update changelog entries for 3.34.1

- gnome-initial-setup/pages/account/um-photo-dialog.c
https://phabricator.endlessm.com/T28364
> Avatar faces in gsettings-desktop-schemas

- gnome-initial-setup/pages/password/gis-password-page.c
Normally the password page is hidden when the "Set a password" checkbox
is left unchecked on the Account page. In
gis_account_page_local_apply(), we call gis_driver_set_username() and
gis_driver_set_passwordless() and these both trigger the
username_or_passwordless_changed() callback in the password page.
However, when the parental controls checkbox on the account page is
checked, gis_driver_set_parental_controls_enabled() is called which
leads to all the pages being destroyed and rebuilt (see
rebuild_pages()), which means we lose the "hidden" state of the password
page when it should be hidden. So call
username_or_passwordless_changed() during construction of the password
page object as well, and use g_signal_connect_swapped() so we can avoid
faking the pspec parameter. …
> fixup! account-local: add toggle for passwordless accounts

- NEWS
- gnome-initial-setup/gis-keyring.c
- gnome-initial-setup/meson.build
- gnome-initial-setup/pages/account/gis-account-page-local.c
- gnome-initial-setup/pages/language/cc-language-chooser.c
- gnome-initial-setup/pages/language/gis-welcome-widget.c
- gnome-initial-setup/pages/password/gis-password-page.c
- meson.build
- po/de.po
- po/ja.po
- po/nb.po
- po/nl.po
- po/ro.po
- po/uk.po
Trivial merge of the upstream 3.36.1 tag (pushed here as `Version_3.36.1`).
https://phabricator.endlessm.com/T29691
> Update to 3.36.1

- gnome-initial-setup/pages/parental-controls/gis-parental-controls-page.c
This should be squashed in when we next rebase.
It reworks the metrics submission for parental controls to use the same
event (data format and UUID) as the event submitted by
malcontent-control when a user’s parental controls are changed. A
`IsInitialSetup` field differentiates the two.
This allows shared code for processing the events on the server, and
allows some more comparisons to be made between initial-setup and
malcontent-control events.
https://phabricator.endlessm.com/T28742
> fixup! eos: Report metrics from parental controls page

- debian/changelog
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
https://phabricator.endlessm.com/T30173
> debian: Rebase on 3.38.0 upstream release

- debian/changelog
No Debian packaging changes were needed.
https://phabricator.endlessm.com/T31523
> T31523 (Debian)

- gnome-initial-setup/pages/account/um-utils.c
Backport of https://gitlab.gnome.org/GNOME/gnome-initial-setup/-/merge_requests/30
https://phabricator.endlessm.com/T33488
> T33488 (eos4.0)

- gnome-initial-setup/gis-page-util.c
This app moved to /usr/libexec thanks to Debian revising its policy on
that directory.
Rather than hardcoding a path, look it up from the .desktop file.
https://phabricator.endlessm.com/T33912
> page-util: Look up eos-installer path from .desktop file

- .tx/config
- po/LINGUAS
- po/bn.po
https://phabricator.endlessm.com/T35124
> Reinstate Transifex configuration & Bengali translation
