endlessm/gnome-initial-setup

gnome-initial-setup/pages/summary/com.endlessm.Tutorial.FBERemote.xml, gnome-initial-setup/pages/summary/gis-summary-page.c
Since the tutorial now has an extra parameter that it expects, we needed
to update the client-side code for it in GIS.
[endlessm/eos-shell#3916]
=> GIS: Updated the code to use the new tutorial's dbus format

gnome-initial-setup/pages/summary/gis-summary-page.c
Old code always started the tutorial with ignore_exit flag set
to true whic was incorrect. Now if the user is already existing,
the proper value is passed.
[endlessm/eos-shell#3916]
=> GIS: Fixed logic for tutorials started as existing user

debian/control, debian/install
Follows process from http://build-common.alioth.debian.org/cdbs-doc.html
for CDBS packages. A wildcard install file is added since there's no
longer a single binary package for gnome-initial-setup.
[endlessm/eos-shell#4451]
=> Add debug package

gnome-initial-setup/gis-driver.c, gnome-initial-setup/gis-driver.h, gnome-initial-setup/pages/language/gis-language-page.c, gnome-initial-setup/pages/location/gis-location-page.c
Kill off DefaultTimeFormat from the personality file by querying the locale via nl_langinfo() instead.
[endlessm/eos-shell#4558]
=> Get time format from locale instead of personality file

gnome-initial-setup/pages/keyboard/Makefile.am, gnome-initial-setup/pages/keyboard/cc-common-language.c, gnome-initial-setup/pages/keyboard/cc-common-language.h, gnome-initial-setup/pages/keyboard/cc-ibus-utils.c, gnome-initial-setup/pages/keyboard/cc-ibus-utils.h, gnome-initial-setup/pages/keyboard/cc-input-chooser.c, gnome-initial-setup/pages/keyboard/cc-input-chooser.h, gnome-initial-setup/pages/keyboard/cc-keyboard-detector.c, gnome-initial-setup/pages/keyboard/cc-keyboard-query.c, gnome-initial-setup/pages/keyboard/cc-keyboard-query.h, gnome-initial-setup/pages/keyboard/cc-util.c, gnome-initial-setup/pages/keyboard/cc-util.h, gnome-initial-setup/pages/keyboard/gis-keyboard-page.c, gnome-initial-setup/pages/keyboard/gis-keyboard-page.h, gnome-initial-setup/pages/keyboard/gis-keyboard-page.ui, gnome-initial-setup/pages/keyboard/input-chooser.ui, po/ar.po, po/es.po, po/fr.po, po/gnome-initial-setup.pot, po/pt_BR.po
Brought from GNOME 3.14.0, this new design simplifies selecting the default layout. It also includes the layout detector.
[endlessm/eos-shell#3364]
=> New keyboard layout selection page

gnome-initial-setup/pages/language/gis-language-page.c
While we can't pinpoint the reason for the barcode disappearing, the
best guess is that sometiumes the cache dir is being created by some
other method that might encounter a race condition with GIS so this fix
makes sure that we have that directory before trying to write the
barcode image to it.
[endlessm/eos-shell#4708]
=> GIS: Possible fix for barcode sometimes not showing up on initial boot

gnome-initial-setup/pages/keyboard/cc-keyboard-query.c, gnome-initial-setup/pages/keyboard/gis-keyboard-page.ui, gnome-initial-setup/pages/keyboard/keyboard-detector.ui, po/ar.po, po/es.po, po/fr.po, po/gnome-initial-setup.pot, po/pt_BR.po
We do not use page icons in other pages, and we loose a valuable space,
specially when running in low resolutions.
[endlessm/eos-shell#3364]
=> keyboard: Remove page icon

gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.c, gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.ui, po/ar.po, po/es.po, po/fr.po, po/gnome-initial-setup.pot, po/pt_BR.po
Other than formal references to the full company name
(Endless Mobile, Inc.), we will simply use the name Endless
(rather than Endless Mobile).
[endlessm/eos-shell#4791]
=> Refer to company as Endless

gnome-initial-setup/pages/account/gis-account-page.ui
It was a bit unintuitive so now it's a checkbox.
[endlessm/eos-shell#4953]
=> Changed "Show password" toggle button to checkbox

gnome-initial-setup/pages/language/Makefile.am, gnome-initial-setup/pages/language/gis-language-page.c, gnome-initial-setup/pages/language/gis-language-page.ui
We just check whether there's a directory at /var/endless-extra and that
it's not empty.
[endlessm/eos-shell#4991]
=> Add basic SD card detection to factory dialog

gnome-initial-setup/pages/language/gis-language-page.c, gnome-initial-setup/pages/language/gis-language-page.ui
Requested for factory processes, so that the operator can verify that
the right image version and country was flashed on the SD card.
[endlessm/eos-shell#4997]
=> Factory dialog: Show SD card version info

gnome-initial-setup/pages/language/eos-test-mode
A couple fixes to make the test mode overlays work more robustly. The split image setup in particular needs to be handled very carefully.
[endlessm/eos-shell#5036]
=> Make test mode more robust

configure.ac
Depend on webkit2gtk-4.0 instead of webkit2gtk-3.0.
[endlessm/eos-shell#5202]
=> build: bump webkit dependency version

debian/control
Depend on libwebkit2gtk-4.0 instead.
[endlessm/eos-shell#5202-debian]
=> Do not depend on libwebkit2gtk-3.0

data/setup-shell.desktop
On systems where the shell might be slow to start up, we need to make
sure gnome-initial-setup launches after the WM has time to initialize.
Copy these lines from gnome-shell's desktop file to get our setup shell
spawned at the right phase.
https://github.com/endlessm/eos-shell/issues/4669
=> setup-shell: Make sure that the shell launches first

gnome-initial-setup/pages/language/eos-test-mode
Ubuntu's Linux 4.1 (a requirement for eos 2.4.0) does not provide the
'overlayfs' filesystem we have been using before the upgrade, but a
compatibility layer implemented on top of the upstream 'overlay'
filesystem (endlessm/linux@a61b539). Since we're moving to a new
codebase in any case, let's just use the upstream version directly.
For both 'overlay' and 'overlayfs' filesystems there is a 'workdir'
mount option that needs to be passed to rw mounts.
[endlessm/eos-shell#4518]
=> Use upstream 'overlay' filesystem

configure.ac
initializing automake. Without this, $install_sh doesn't get expanded
properly, causing errors like:
/bin/sh: /home/kalev/install-sh: No such file or directory
install: cannot create regular file ‘/media/build/gnome/_jhbuild/root-gnome-initial-setup/media/build/gnome/share/locale/af/LC_MESSAGES/gnome-initial-setup.mo’: No such file or directory
Related: https://bugs.freedesktop.org/show_bug.cgi?id=66413
[endlessm/eos-shell#5434]
=> This reorders the macros so that AC_USE_SYSTEM_EXTENSIONS comes after

gnome-initial-setup/pages/keyboard/cc-input-chooser.c, gnome-initial-setup/pages/keyboard/gis-keyboard-page.c
Patches cherry picked from upstream (https://bugzilla.gnome.org/show_bug.cgi?id=737493)
[endlessm/eos-shell#5543]
=> Fix crashes when no keyboard layout selected

gnome-initial-setup/pages/network/gis-network-page.c
This happens because, in this situation, the network page can be destroyed (automatically, due to the language change) before the GSource callback for `refresh_again()`, installed on a timeout, had been called, causing that callback to access an invalid instance of GisNetworkPage, resulting in a crash.
[endlessm/eos-shell#5438]
=> Fix crashes when changing locales while Wifi connectivity is unavailable

gnome-initial-setup/gis-driver.c, gnome-initial-setup/gis-driver.h, gnome-initial-setup/pages/language/gis-language-page.c, gnome-initial-setup/pages/location/gis-location-page.c
The image builder now sets the system defaults, so there's no need to read them from the personality file.
[endlessm/eos-shell#4652]
=> Don't use language and timezone defaults from personality file

gnome-initial-setup/pages/language/gis-language-page.c
Always reset the org.gnome.system.locale.region GSetting property when
running g-i-s, to ensure that the language used for region-dependant
format strings is consistent with the language selected by the user.
[endlessm/eos-shell#5617]
=> language: Ensure that the locale region matches user's selected language

gnome-initial-setup/pages/language/eos-test-mode
Our usage of /endless and /var/endless-extra has changed some since the
test-mode script was first created.
* /endless is no longer an overlayfs but a symlink farm
* /var/endless-extra is no longer mounted read only
This requires overlays to be mounted over /endless and
/var/endless-extra so that app installation activity is not persistent.
The toplevel /endless directory can be easily handled with the existing
loop. /var/endless-extra needs some additional special handling since
/var is also a scratch overlay. It needs to be unmounted and remounted
around the /var overlay mount, and then an overlay needs to be mounted
on /var/endless-extra.
[endlessm/eos-shell#6152]
=> test-mode: Update /endless handling with symlink farm

gnome-initial-setup/gis-driver.c
The current code checks for height < 800, which would be
better if we check for height < 600 and width < 800. Also,
when the screen is big, don't allocate a window bigger than
it used to be.
[endlessm/eos-shell#5924]
=> window: detect and adapt to small screens betters

data/Makefile.am
Run FBE only for the very first user account on the system, the first
time the system boots, and never for new user accounts.
[endlessm/eos-shell#3727]
=> Don't run first boot experience for new user accounts

gnome-initial-setup/pages/keyboard/cc-input-chooser.c
If the GCancellable is cancelled by the finalize() function, the
callback will still be called potentially with an instance of the
CcInputChooser that's not valid anymore.
To avoid crashing in that case, only access the priv pointer of
CcInputChooser when we have no error.
[endlessm/eos-shell#6362]
=> input-chooser: don't access priv pointer before checking no error

po/LINGUAS
Fixes the missing symlink that was intended to provide the zh_CN
fallback translations for missing strings in zh_TW and zh_HK.
[endlessm/eos-shell#6381]
=> Add zh to LINGUAS

gnome-initial-setup/gnome-initial-setup.c
Since we don't run GTK+ anymore, we have to do this manually, else the
tutorial will always start in English.
https://phabricator.endlessm.com/T3727
=> Initialize locales in existing user mode

gnome-initial-setup/pages/language/gis-language-page.c, gnome-initial-setup/pages/language/gis-language-page.ui
Useful on ARM, where the value of this string can be used to verify
that the right device tree is being used.
https://phabricator.endlessm.com/T11017
=> Factory dialog: show device-tree compatible string

gnome-initial-setup/pages/language/cc-language-chooser.c
The current sorting function mistakenly tries to
compare row a with itself, instead of row a and b.
Fix that by properly gathering data from row a and b.
https://phabricator.endlessm.com/T11756
=> language-chooser: compare rows correctly

gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.c, gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.ui
Update strings and function names to capture the new terminology for replacing
your OS entirely with Endless: reformat. This should be less ambiguous than
having two user-visible processes known as install, the Windows dual-boot
process (non-destructive, reversible) and the Linux reformat process (very
destructive, non-reversible).
https://phabricator.endlessm.com/T13654
=> replace install{,er} with reformat{,ter}

gnome-initial-setup/pages/live-chooser/eos-setup-live-user
For allowing to update the settings of a component that is not the
shell these changes also reimplement how the gsettings overrides
are implemented inside eos-setup-live-user. It should now be easy to
add any new modules that need their gsettings overridden.
https://phabricator.endlessm.com/T13950
=> eos-setup-live-user: Disallow updates on GNOME Software

gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.ui
The metrics label is being treated separatedly of the check button,
which makes it not change the checkbutton state when the label is
clicked.
This behavior breaks the standard, expected behavior and can be very
frustrating, specially when the user doesn't have professional skills
with the mouse.
Fix that by putting the label inside the checkbutton.
https://phabricator.endlessm.com/T13578
=> endless-eula: put the metrics label inside the checkbutton

gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.c, gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.ui
Unfortunately, there are changes on master which prevent the same patch applying cleanly to both, so here is a eos3.0-specific patch.
https://phabricator.endlessm.com/T13890
=> eula: disable metrics on live systems

gnome-initial-setup/pages/network/gis-network-page.c
When showing the Network page on the initial setup,
the list of Wi-Fi connections is displayed even when
there's an ethernet cable available.
Fix that by skipping the page when any ethernet device
if detected.
https://phabricator.endlessm.com/T13749
=> network: skip page when ethernet cable is available

gnome-initial-setup/pages/network/gis-network-page.c
When the Initial Setup starts up and we detect a working connection,
the WiFi list isn't populated. If it happens that the computer is
disconnected before reaching the network page, we show the page again,
but nothing is set so the user effectively gets stuck in that page
forever.
Fix that by setting up the wifi device even if there's a connection
available.
https://phabricator.endlessm.com/T13749
=> network: populate wifi list even when already connected

gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.c
Run the eos-google-chrome-system-helper.py helper via pkexec which
touches a stamp file, making the automatic download of Google Chrome in
the user's session a no-op. The download/install consumes 250MB of
RAM from the tmpfs!
https://phabricator.endlessm.com/T15370
=> T15370: disable chrome download when entering live mode

gnome-initial-setup/pages/account/account.css, gnome-initial-setup/pages/account/account.gresource.xml, gnome-initial-setup/pages/account/gis-account-page.c
The old password strength validation only starts giving us any
value when the password already has a good strength. This behavior
led to confusion, as it only actually works when after typing a
few random characters, making us think it wasn't working at all.
The new password scheme is just a minor extension of the old one.
Basically, whenever a password is typed, we make sure the strength
to be at least one - instead of 0 like before.
Now, we use the following scheme:
Empty	  -> 0 bars
Weak	  -> 1 bar (red)
Regular	  -> 2 bars (yellow)
Strong	  -> 3 bars (green)
Excellent -> 4 bars (blue)
This makes the feedback much more immediate, and improves the overall
interaction with the initial setup page.
https://phabricator.endlessm.com/T15307
=> account: implement the new password strength scheme

gnome-initial-setup/pages/live-chooser/eos-setup-live-user
The code assumed that only icon-grid-prepend-C.json would exist, whereas actually the prepend files can be created with any locale name (although they are not at present). To ensure the reformatter always appears, we add a glob/loop similar to remove_chrome_from_icon_grids, but always create icon-grid-prepend-C.json if it does not exist.
https://phabricator.endlessm.com/T15643
=> eos-setup-live-user: Fixup live image icon grid prepend for non-C locales

gnome-initial-setup/pages/keyboard/cc-input-chooser.c
When no more specific keyboard layouts have been found, add us and
us+intl as fallback options, instead of an empty list.
https://phabricator.endlessm.com/T15660
=> keyboard: add us/us+intl default layouts as fallback

gnome-initial-setup/pages/language/eos-test-mode
The unit files in eos-updater were recently changed, so that
eos-updater.service is now a unit in its own right, not an alias for
eos-autoupdater.service. Change the unit file handling to reflect that.
https://phabricator.endlessm.com/T15977
=> eos-test-mode: Update eos-updater unit usage

gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.c
The gnome-initial-setup user creates a keyring for itself with the
passphrase 'gis'; this function updates the passphrase. The keyring is
then moved into the newly-created user's homedir when they log in, by
gnome-initial-setup-copy-worker.
(In the normal, non-live FBE flow, the keyring password is updated to
match that of the newly-created account, and the password is written in
plaintext to /run/gnome-initial-setup/.config/password. After moving the
keyring into position, copy-worker attempts to read this file and unlock
the keyring. We bypass the whole 'account' page, so this logic is
skipped.)
https://phabricator.endlessm.com/T15938
=> live-chooser: set keyring password to empty string

gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.c
GisPageClass.save_data is called for each page when the last page of the FBE is reached.
By deferring this to the end of the FBE, and calling it exactly once, we can change the daemon's defaults to "collect, but don't submit". If the user chooses to leave metrics enabled, we set the daemon to "collect and submit". If the user disables metrics, we set the daemon to "neither collect nor submit".
This allows boot-time metrics to be collected during the first boot, but only submitted once the user has had a chance to opt out. (The previous default was "submit, but don't collect", which meant we lost valuable information from the first boot.)
For the corresponding change to the default configuration, see https://github.com/endlessm/eos-event-recorder-daemon/pull/215 …
=> endless-eula: set metrics state when FBE complete

gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.c
This is a partial revert of #141. I left out the hunk which assigned an ID to the separator in the .ui file -- nice to have that, even if it's currently unused.
We previously had to disabled metrics on live systems because boot-time events (such as the fact that the system is live!) were lost on the first boot (ie every boot of a live system). Since the usage pattern of a live system is expected to be very different to a persistant installation, we need to be able to distinguish the two. Now that T14065 is resolved, this event will not be lost, so distinguishing live systems is possible, so we can re-enable metrics (by default) on live systems.
https://phabricator.endlessm.com/T14217
=> Re-enable metrics on live systems

gnome-initial-setup/pages/keyboard/cc-input-chooser.c, gnome-initial-setup/pages/language/gis-language-page.c
This PR address a possible race between `setenv` and `getnev` manually copy the environment and adding `LC_MESSAGE` environment variable instead of relying on environment inheritance.
Ticket https://phabricator.endlessm.com/T17304
=> manually set LC_MESSAGES

gnome-initial-setup/pages/summary/gis-summary-page.ui
Unscientific straw polls of the London team concluded that this is about the right point to wrap the text, and that a little extra margin below makes the elements look more balanced.
https://phabricator.endlessm.com/T17622
=> summary: limit width of live mode warning

gnome-initial-setup/pages/keyboard/input-chooser.ui
CCInputCooser widget needs to expand when the user wants to see
more keyboard layouts.
https://phabricator.endlessm.com/T17605
=> input-chooser: allow CcInputChooser to expand

gnome-initial-setup/pages/live-chooser/eos-setup-live-user
In the Great GNOME Shell Rebase of Spring 2017, our downstream taskbar-pins GSetting was abandoned in favour of re-using upstream's favorite-apps GSetting.
Interestingly, without this change, the result is that only the reformatter appears on the taskbar! This is because the Shell imports the taskbar-pins key to favorite-apps, if it is not empty. The default is now empty; this script adds a single icon to it. :)
I also took this opportunity to fix some Python style problems.
https://phabricator.endlessm.com/T17622
=> Fix adding the reformatter to the taskbar

gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.ui
Previously, in English (and possibly other languages), the two columns are
allocated different widths (310 vs 289 px). This in turn leads to the two
labels ("Try Endless OS by running it from the USB stick" and
"Reformat this computer with Endless OS") to be allocated different
heights, even though they are in the same vertical size group, and even
though both strings only actually occupy two lines. The narrower label was
allocated extra height for a third line of text.  This has the knock-on
effect of the icon and the buttons not being vertically aligned.
I think this might be an interaction with height-for-width? Quoth the
GtkSizeGroup documentation:
> Note that size groups only affect the amount of space requested, not
> the size that the widgets finally receive. If you want the …
=> live-chooser: ensure both columns have the same width

configure.ac, gnome-initial-setup/Makefile.am, gnome-initial-setup/gnome-initial-setup.in, gnome-initial-setup/setlocale-wrapper.c
When a user chooses a different language in the first screen of
gnome-initial-setup, the web view provided by GNOME Online Accounts
will still display the original language in which the app has been
launched. This is obviously an issue for users who may find it hard
to connect to their online accounts because of not using their
language.
Since the web view is controled by a different library, the cleanest
way to make it obey the language change is to override the set_locale
function (using LD_PRELOAD) and make it return the language that the
user has set.
Because of this I have had to wrap the gnome-initial-setup binary in
a script that sets up the environment variable before calling the real
executable.
https://phabricator.endlessm.com/T18041
=> Ensure GOA displays the web view in the selected language

gnome-initial-setup/gis-driver.c
The g-i-s is a top priority application and one that should be
left idle, so it makes sense to keep the user focused on it and not
let the system be idle either (it's not a great UX if the user sees the
lock screen's shield on first boot).
https://phabricator.endlessm.com/T18045
=> Inhibit the idle state when running g-i-s

gnome-initial-setup/Makefile.am
Without these, building from a tarball fails because
gnome-initial-setup.in does not exist, and make distcheck additionally
fails because gnome-initial-setup/gnome-initial-setup is left over after
`make clean`.
https://phabricator.endlessm.com/T18041
=> Distribute g-i-s.in, clean generated wrapper

gnome-initial-setup/pages/timezone/gis-timezone-page.c
When the user changes the locale, then the clock format in the timezone
page should reflect that, but it was apparently always using the initial
(global) locale.
These changes make sure that we get the clock format for the currently
set locale, which will honor what the user has previously chosen inside
g-i-s.
https://phabricator.endlessm.com/T17468
=> timezone: Fix displaying the right clock format

gnome-initial-setup/Makefile.am
From OBS:
libtool: link: gcc -shared  -fPIC -DPIC  .libs/setlocale-wrapper.o    -O2 -Wl,-Bsymbolic-functions -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,defs -Wl,-O1 -Wl,--as-needed   -Wl,-soname -Wl,libsetlocale-wrapper.so.0 -o .libs/libsetlocale-wrapper.so.0.0.0
.libs/setlocale-wrapper.o: In function `setlocale':
/usr/src/packages/BUILD/gnome-initial-setup-3.22.1+dev177.e4922f5/gnome-initial-setup/setlocale-wrapper.c:37: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
Makefile:593: recipe for target 'libsetlocale-wrapper.la' failed
I cannot reproduce this by building the debian package locally but there we are.
https://phabricator.endlessm.com/T18041
=> setlocale-wrapper: pass -ldl to linker

gnome-initial-setup/pages/language/Makefile.am, gnome-initial-setup/pages/language/cc-common-language.c
Instead of hardcoding the initial list, we can use vendor.conf to seed
it; we still use the hardcoded defaults when that's not the case.
https://phabricator.endlessm.com/T17467
=> language: allow to specify initial languages from vendor.conf

gnome-initial-setup/pages/language/cc-language-chooser.c
It could be confusing to have to scroll back to see other languages;
make sure the initial language is always the first in the list.
https://phabricator.endlessm.com/T17467
=> language: make sure initial language is always at the top

gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.c
https://github.com/endlessm/gnome-initial-setup/pull/161 changed g-i-s
to only set the metrics enabled state at the end of the FBE; the change
from commit 21076e25ea62b4177c6c67c518254d7c4cbf5425 was lost during
our rebase for eos3.2. Make sure to apply that code again.
https://phabricator.endlessm.com/T18943
=> endless-eula: fix regression when setting metrics state

configure.ac, gnome-initial-setup/gis-driver.c, gnome-initial-setup/gis-driver.h, gnome-initial-setup/gis-page-util.c, gnome-initial-setup/gis-page-util.h, gnome-initial-setup/pages/language/gis-language-page.c
This is not as aesthetically pleasing as using UDisks and will produce incorrect results if a non-eosdvd ISO (ie base – no others fit) is written to DVD or an eosdvd ISO is written to USB.
But the UDisks approach does not actually work: when booted from a DVD, for annoying reasons the udev properties indicating the media in the drive are missing for the DVD device, so UDisks doesn't believe it to be an optical device.
This approach is simpler and easier to test.
I reused (and deduplicated) the logic used to trigger the demo mode label. I gave it a quick spin in all these conditions:
* `/sysroot` has `eos-image-version` `eosoem-foo`, not live mode => label
* `/sysroot` has `eos-image-version` `eosoem-foo`, live mode => no label, Ctrl-D does nothing
* `/sysroot` has no `eos-image-version`, …
=> driver: determine DVD-ness from image version

debian/control, debian/control.in
This reverts commit 4d0a66098fcff2d1a6be782374e3aa4eac7feecb.
Depends on https://github.com/endlessm/gnome-initial-setup/pull/212
https://phabricator.endlessm.com/T18708
=> Revert "Add libudisks2 dependency"

gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.c
But make it invisible in that case; this ensures we still call
set_enabled() at the end of the FBE to definitively disable metrics.
https://phabricator.endlessm.com/T19227
=> endless-eula: create page also in demo mode

gnome-initial-setup/gnome-initial-setup.c
Upstream has "existing user" mode for new user accounts, but we don't
want that in Endless, so skip it. In the future, we should be launching
the tutorial right from here, once it's again available.
This change was introduced to fix T3727, but got lost during the rebase
to EOS 3.2. It's way simpler now because we don't have a tutorial now,
but in the near future should probably be reworked to launch the new
tutorial, once it's ready.
https://phabricator.endlessm.com/T19802
=> Don't run gnome-initial-setup for existing users

debian/control
We're now reporting a metric
https://phabricator.endlessm.com/T18983
=> debian: Depend on eos-metrics-0-dev

data/initial-setup.json, gnome-initial-setup/pages/live-chooser/eos-setup-live-user, gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.c
At present, there is no obvious way to shut down the system from the
FBE. (The factory test dialog, accessed with Ctrl+F on the first page,
does provide a Power Off button, but this is not user-visible.) This is
annoying if you've booted an Endless OS machine but want someone else to
complete the FBE. It's worse if you're on a live USB and are running the
reformatter, because it does not provide any way to cleanly shut down
the system short of reformatting your system!
Upstream, the power-off options are in the aggregateMenu, but in Endless
they've been moved to the Endless-specific userMenu component. We have
also introduced an Endless-specific powerMenu component for use at the
GDM login screen, so we can just add it to the initial-setup shell mode.
This adds a power-off button to the …
=> Add powerMenu to initial-setup shell mode

gnome-initial-setup/eos-transient-setup, gnome-initial-setup/gis-driver.c, gnome-initial-setup/gis-driver.h, gnome-initial-setup/gis-page-util.c, gnome-initial-setup/gis-page-util.h, gnome-initial-setup/pages/language/gis-language-page.c, gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.c
Historically, eosinstaller images did not include gnome-initial-setup.  Instead, the eos-installer-standalone package installed replacement files to cause gdm to launch eos-installer directly, instead.
This avoided any changes to gnome-initial-setup itself. But unfortunately it introduced its own problems: gnome-initial-setup is moderately coupled to the corresponding versions of gdm and gnome-shell, so eos-installer's copies of the initial-setup session and shell mode had to be manually kept in sync with each GNOME rebase.
Since this was originally implemented, we added support for combined live + installer images, and taught gnome-initial-setup how to launch eos-installer. At this point, it is simpler to include the real gnome-initial-setup in eosinstaller images, too, and make it …
=> Adjust for use on eosinstaller images

gnome-initial-setup/gis-assistant.c, gnome-initial-setup/gis-page-util.c, gnome-initial-setup/gis-page-util.h, gnome-initial-setup/pages/language/gis-language-page.c, gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.c
Previously, on reformatter-only images, the language page would advance to the live-chooser page, which would immediately hide the FBE and launch eos-installer. When that process exited, the live-chooser page would re-show the FBE and move to the language page.
As well as being awkward, if animations are enabled (as they are on most non-VM systems) then the transition back to the language page is not instantaneous, so you see a flash of the live-chooser page when eos-installer exits.
To solve this, move the hide-launch-wait-reshow logic to gis-page-util, and launch eos-installer directly from the language page when the user clicks Next. To avoid actually advancing to the next page, we (ab)use the ->apply() vfunc, which is intended to be used by pages like the keyboard page which need to …
=> Improve transition between FBE and eos-installer on eosinstaller images

gnome-initial-setup/pages/password/gis-password-page.c
Upstream won't let users create an account if the password is considered
too weak (i.e. "bad"), but we don't want to be that restrictive, so let's
remove that requirement and simply consider a password good enough as
long as it's a non-empty string.
https://phabricator.endlessm.com/T22042
=> password: Relax requirements to validate the password page

gnome-initial-setup/pages/account/gis-account-page-local.c, gnome-initial-setup/pages/account/gis-account-page-local.h, gnome-initial-setup/pages/account/gis-account-page-local.ui, gnome-initial-setup/pages/account/gis-account-page.c
If a vendor wants to have passwordless accounts by default, then they
should be able to set that in the vendor configuration file.
This patch allows that by using the "show-password-switch" option in the
"page.account" group.
https://phabricator.endlessm.com/T23326
=> account: Check configuration to hide password switch if needed

gnome-initial-setup/gis-driver.c, gnome-initial-setup/gis-driver.h, gnome-initial-setup/gnome-initial-setup.c, gnome-initial-setup/pages/account/gis-account-page.c, gnome-initial-setup/pages/branding-welcome/gis-branding-welcome-page.c
Accessing the vendor configuration is a common need of many pages, so
pages shouldn't have to always deal with the key file directly as it
leads to a lot of repeated code (for error checking and such). This
patch allows that by abstracting the configuration specifics in a few
functions in the GisDriver.
https://phabricator.endlessm.com/T23483
=> Abstract how vendor configuration is accessed

meson.build
g-i-s uses libsecret's unstable API, so we need to define the macro
SECRET_API_SUBJECT_TO_CHANGE in order for that API to be included.
This change had been forgotten when we ported the build to Meson.
https://phabricator.endlessm.com/T23515
=> build: Add special macro for using libsecret's unstable API

gnome-initial-setup/eos-transient-setup
On live systems, the free "disk" space is, per tmpfs's default, half of
physical RAM. If the system only has 2GB of RAM, then reserving 500MB
(the default) free means there's at 500MB for installing apps. This is
overly restrictive, particularly since it's not such a big deal to run
out of "disk" space on a live system. So, disable this limit.
We have downstream logic in flatpak-dir.c to migrate from setting
-percent to -size. This means that some combinations of these settings
turn out to be "unstable", in the sense that flatpak-dir.c will alter
them whenever the system helper (or root) happens to open the repo:
-size | -percent | ostree-repo.c      | flatpak-dir.c
------ | -------- | ------------------ | -------------------------------------
non-0 | *        | -size applies      | no …
=> eos-transient-setup: set min-free-space-* to 0

gnome-initial-setup/meson.build
The gis-page-util resources had been left out when the project was moved
to meson. As a result doing Ctrl+F for getting the factory dialog didn't
work.
https://phabricator.endlessm.com/T23813
=> Compile gis-page-util resources

gnome-initial-setup/gis-page-util.c, gnome-initial-setup/gis-page-util.ui
A partner has requested that we provide an indication in this dialog
of which image personality (language) was flashed.
Add the image name stamp to this dialog which includes the
personality name at the end. The same thing was already being
shown for the SD card.
https://phabricator.endlessm.com/T23690
=> Show image version in factory dialog

data/20-gnome-initial-setup.rules
This was added in 244f7a745, in 2017, so it evidently hasn’t caused any
problems — but having the bracket in the wrong place was causing
DemoMode action IDs to not be matched here for their initial-setup
polkit fast pass.
=> data: Fix a string matching typo in the polkit rules

gnome-initial-setup/pages/timezone/gis-timezone-page.c
Previously, unless the following was specified in the vendor config
file:
[page.timezone]
show-if-detected=false
then the timezone selection page would be shown even if the location was
detected via Geoclue.
The argument for skipping the page if location has been detected in some
Endless images is that this makes the FBE process nicer enough to risk
sometimes silently selecting the wrong timezone.  If we believe this for
some users, without any data about how often the wrong timezone is
selected, then we should apply this behaviour for all systems.
This patch switches the default setting to skip the timezone page if
location was detected. The old behaviour can be re-enabled by specifying
the following in the vendor config file:
[page.timezone]
show-if-detected=true …
=> timezone: hide by default if location was detected

gnome-initial-setup/gis-assistant.c, gnome-initial-setup/gis-assistant.ui, gnome-initial-setup/pages/network/gis-network-page.c, gnome-initial-setup/pages/site/gis-site-page.c, gnome-initial-setup/pages/timezone/gis-timezone-page.c, gnome-initial-setup/pages/timezone/gis-timezone-page.ui
If we have already retrieved a location from the network when it comes time to show the timezone page, we skip it entirely. But in practice, it is quite easy to reach the timezone page before the location has been retrieved, even after configuring a wireless network.
On the network page, we would previously change the grey **Skip** button to a blue **Next** button as soon as the network connection came up. But GeoClue waits for NM's connectivity check to succeed before requesting location from the network. Even on a good network, the connectivity check (a simple HTTP request to a Linode VM) may be essentially instantaneous, or may take a few hundred milliseconds, or may take 10 seconds or more. Tweak this page to wait for the connectivity check to finish (or for a timeout, whichever comes …
=> Improve timezone detection when connectivity check is slow

gnome-initial-setup/eos-transient-setup
This has recently been added to the normal user profile in
eos-theme.git, so should be added here too so that the demo/live
sessions have the same set of default dconf settings as the normal
sessions.
https://phabricator.endlessm.com/T20990
=> eos-transient-setup: Add file-db path for dconf defaults from OSTree

gnome-initial-setup/pages/summary/gis-summary-page.c
GDM can't tell Plymouth to quit until gnome-initial-setup connects to
it, so GDM knows gnome-initial-setup has started successfully. Currently
gnome-initial-setup only connects to GDM once the user clicks the "Start
Using $DISTRO" button on the last page, to switch over to the
newly-created user. This prevents accessing the TTY for the whole time
gnome-initial-setup is running and makes systemd account the time spent
in gnome-initial-setup as part of the boot process.
Connecting to GDM as soon as gnome-initial-setup starts allows GDM to
tell Plymouth to quit at the right time, avoiding the problems described
above.
https://phabricator.endlessm.com/T21181
=> Connect to GDM as soon as gnome-initial-setup starts

gnome-initial-setup/gis-driver.c, gnome-initial-setup/gis-driver.h, gnome-initial-setup/pages/summary/gis-summary-page.c
GDM can't tell Plymouth to quit until g-i-s connects to it, so GDM knows
g-i-s has started successfully. Currently g-i-s only connects to GDM on
the last page, when it logs-in the new user. This prevents accessing the
TTY and makes systemd account the time spent in g-i-s as part of the
boot process.
Connecting to GDM as soon as g-i-s allows GDM to tell Plymouth to quit
at the right time, avoiding the problems described above.
Closes: https://gitlab.gnome.org/GNOME/gdm/issues/439
https://phabricator.endlessm.com/T21181
=> driver: Connect to GDM as soon as g-i-s starts

gnome-initial-setup/gis-driver.c
JP's original patch was correct, but I amended
7383c717fd13ca418dd0b97d3a4dedb0dbd1dd65 to change "!error" to a
comparison to "NULL". Unfortunately I got the comparison backwards.
https://phabricator.endlessm.com/T21181
=> driver: fix sense of error check when connecting to GDM

gnome-initial-setup/gnome-initial-setup-copy-worker.c, gnome-initial-setup/meson.build
libgnome-keyring has been dropped from Debian in favour of applications
using libsecret.
<https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892359>
libsecret does not provide a straightforward API to unlock a keyring
with a given passphrase, but we can do it with gnome-keyring's
InternalUnsupportedGuiltRiddenInterface, which gis-keyring.c uses to set
the passphrase on the login keyring in the first place.
This should be squashed into 'copy-worker: Unlock keyring on first
login' in the next rebase.
https://phabricator.endlessm.com/T26274
=> Unlock keyring using libsecret + internal D-Bus API

debian/changelog, debian/control, debian/control.in
This library has been removed from Debian; we have reimplemented our
downstream code that used it in terms of libsecret and an internal
gnome-keyring D-Bus API.
Counterpart to #282.
https://phabricator.endlessm.com/T26274
=> Drop libgnome-keyring dependency

data/20-gnome-initial-setup.rules
This is necessary in order for the Site page to be able to save its data
to /etc/metrics/location.conf.
https://phabricator.endlessm.com/T27787
=> Allow gnome-initial-setup user to run eos-write-location

gnome-initial-setup/gis-assistant.ui
3857805 added this style class to the "Next" button, and removed code
that would set this class depending on whether the widget is sensitive.
At the time I overlooked that the suggested-action style class should
also be present for the "Accept" button on the EULA page: I think it's
correct to say that accepting the EULA is the suggested action.
There is a third button which may appear in this position: "Skip". This
is used (for example) on the Wi-Fi configuration page when no network is
selected. It's correct not to mark this button as suggested: the
suggested action is to configure a Wi-Fi network.
https://gitlab.gnome.org/GNOME/gnome-initial-setup/merge_requests/61
https://phabricator.endlessm.com/T27790
=> assistant: mark "Accept" button as suggested action

gnome-initial-setup/pages/network/gis-network-page.c
A clean backport of
https://gitlab.gnome.org/GNOME/gnome-initial-setup/merge_requests/69,
complicated only by my own downstream conflicting change. This branch
reverts that change, backports !69, and then applies a refreshed version
of that patch which I have posted to
https://gitlab.gnome.org/GNOME/gnome-initial-setup/merge_requests/74.
https://phabricator.endlessm.com/T27527
=> network: react to devices being connected

gnome-initial-setup/pages/account/gis-account-page-local.ui
Fix horizontal alignment of "Set a password" checkbox. This should be
squashed on the next rebase.
https://phabricator.endlessm.com/T29552
=> fixup! account-local: add toggle for passwordless accounts

gnome-initial-setup/pages/account/gis-account-page-local.c
In gis-account-page-local.c, if parental controls are enabled we create
an administrator account which will be used by the parent, and we create
it before the child's account so that the system will not be left
without any admin accounts in case g-i-s crashes or otherwise doesn't
finish. However this isn't especially helpful since the account is not
set to be passwordless (ACT_USER_PASSWORD_MODE_NONE) so cannot easily be
used if the user doesn't make it to the page where they are asked to set
a password on it. So, set the admin account to
ACT_USER_PASSWORD_MODE_SET_AT_LOGIN temporarily. When a password is set
on the account by the password page, accountsservice will set it to
ACT_USER_PASSWORD_MODE_REGULAR.
This seems like a slightly better policy than making the account
passwordless, …
=> account: Make admin account usable in case of errors

gnome-initial-setup/gis-driver.c
These are cherry picks from this upstream MR: https://gitlab.gnome.org/GNOME/gnome-initial-setup/-/merge_requests/80
https://phabricator.endlessm.com/T28787
=> Fix crashes when saving parental controls settings

gnome-initial-setup/pages/password/gis-password-page.c, gnome-initial-setup/pages/password/gis-password-page.ui
Make the "show password" icon match the one in GNOME Shell, rather than
being reversed.
https://phabricator.endlessm.com/T29262
=> fixup! password: Add eye icons to toggle password visibility

gnome-initial-setup/pages/parental-controls/gis-parental-controls-page.c, meson.build
If the user chooses to enable parental controls when setting up the
computer, send a metrics event which contains the initial parental
controls settings. Don’t send an event if parental controls are not
enabled.
This will give us an idea of the more and less popular parental controls
features. If they are compared against parental controls settings set or
changed after initial setup, this metric will also give us an idea of
how people change their parental controls (presumably tweaking them
since they set them incorrectly in the first place).
This commit should not be upstreamed.
https://phabricator.endlessm.com/T28742
=> eos: Report metrics from parental controls page

gnome-initial-setup/pages/keyboard/cc-input-chooser.c, gnome-initial-setup/pages/keyboard/gis-keyboard-page.c
Trivial cherry-pick of the two commits from https://gitlab.gnome.org/GNOME/gnome-initial-setup/-/merge_requests/82.
https://phabricator.endlessm.com/T27791
=> T27791 Fix use of uninitialised memory with input chooser

gnome-initial-setup/pages/account/um-photo-dialog.c
The upstream setting name is 'avatar-directories' now
https://phabricator.endlessm.com/T29718
=> fixup! account: Use control-center setting to override faces

data/initial-setup.json
The panel customizations from Endless are now done as part of panel extension so let's enable it here.
Note we don't change the default panel layout defined for the session, but that is because the panel extension will ignore it (and define its own layout) and if the panel extension fails to load we fallback to the layout set here instead of breaking the session.
See also https://github.com/endlessm/eos-panel-extension/pull/3 (**not** a hard dep).
https://phabricator.endlessm.com/T30445
=> Use panel extension on session

debian/changelog, debian/control, debian/control.in
This accounts for differences in package naming between Endless and
Debian; this can be dropped when T30746 is fixed (see also T30173).
https://phabricator.endlessm.com/T30173
=> debian: Change malcontent recommends to malcontent-data

gnome-initial-setup/pages/account/um-realm-manager.c, gnome-initial-setup/pages/language/gis-welcome-widget.c, gnome-initial-setup/pages/timezone/gis-timezone-page.c
These won’t fix T30173 but make debugging it a little less noisy.
All upstream in https://gitlab.gnome.org/GNOME/gnome-initial-setup/-/merge_requests/103 except the `UmRealmManager` fixes which fix a bug introduced in our downstream commit “copypasta code: Use GTask in UmRealmManager”.
=> T30173 Misc use-after-free fixes

gnome-initial-setup/pages/account/gis-account-page-local.c, gnome-initial-setup/pages/account/gis-account-page-local.h, gnome-initial-setup/pages/account/gis-account-page.c
This reverts commit 2c7590a6f51c6c942c93a02fb8e26716efe42f36.
This was used only by Hack, and we are removing that configuration (https://github.com/endlessm/eos-image-builder/pull/899).
https://phabricator.endlessm.com/T29974
=> Revert "account: Check configuration to hide password switch if needed"

gnome-initial-setup/gis-driver.c
This reverts commit 7eb144d7a3e2a8393e079e78318393a8091f12a3.
It was decided upstream
(https://gitlab.gnome.org/GNOME/gnome-initial-setup/-/merge_requests/96)
that this patch actually makes things worse for those devices, as
without this patch small screen mode would be triggered on the devices
in question, which should make the g-i-s pages scrollable.
See https://phabricator.endlessm.com/T27792
=> Revert "driver: Make height 768 the threshold for "small screens""

debian/changelog, debian/control, debian/control.in
This reverts commit 3b0f7ff42e9df01897a44cb6acf70b1edefaa5f5. We're now
addressing the packaging delta with Debian and malcontent-data will no
longer exist.
https://phabricator.endlessm.com/T30746
=> Revert "debian: Change malcontent recommends to malcontent-data"

data/20-gnome-initial-setup.rules.in, gnome-initial-setup/cc-common-language.c, gnome-initial-setup/gis-driver.c, gnome-initial-setup/gis-driver.h, gnome-initial-setup/gis-page-util.c, gnome-initial-setup/gis-page-util.h, gnome-initial-setup/meson.build, gnome-initial-setup/pages/account/gis-account-page-local.c, gnome-initial-setup/pages/account/gis-account-page-local.ui, gnome-initial-setup/pages/account/um-realm-manager.c, gnome-initial-setup/pages/account/um-utils.c, gnome-initial-setup/pages/keyboard/cc-input-chooser.c, gnome-initial-setup/pages/language/cc-language-chooser.c, gnome-initial-setup/pages/language/gis-language-page.c, gnome-initial-setup/pages/parental-controls/gis-parental-controls-page.c, gnome-initial-setup/pages/password/gis-password-page.c, gnome-initial-setup/pages/timezone/gis-timezone-page.c, meson.build
This reintroduces the majority of our downstream functionality from eos5.1 that we want to preserve. There are 3½ conspicuous gaps:
- factory dialog, accessed by pressing Ctrl+f on the first page
- live boot support & invoking eos-installer on eosinstaller images (which are entwined)
- the eula page
- transifex goop
I'll bring these back in later PRs but they are more involved than the other changes, due to the GTK 4 port.
I first rebased our existing changes onto the latest 41.x point release, not because I plan to merge that rebase but because helped apply them to this new baseline. I have made notes on what I dropped, squashed, and split on the following PR:
- https://github.com/endlessm/gnome-initial-setup/pull/343
So this PR is the result of rebasing that series onto `master`. It …
=> Reintroduce most still-relevant downstream changes atop 43

data/20-gnome-initial-setup.rules.in, gnome-initial-setup/gis-driver.c, gnome-initial-setup/gis-factory-dialog.c, gnome-initial-setup/gis-factory-dialog.gresource.xml, gnome-initial-setup/gis-factory-dialog.h, gnome-initial-setup/gis-factory-dialog.ui, gnome-initial-setup/gis-page-util.c, gnome-initial-setup/gis-page-util.h, gnome-initial-setup/meson.build, gnome-initial-setup/pages/keyboard/cc-input-chooser.c, gnome-initial-setup/pages/language/gis-language-page.c, po/POTFILES.in
This is spiritually a forward-port of 7e692863 and 7f409293, but is in practice almost a total rewrite:
- Port to GTK 4.
- Use GtkShortcut for keyboard shortcut, in place of removed
GtkAccelGroup API. We cannot use gtk_widget_class_add_binding on the
GisLanguagePageClass because we apparently need to handle the event in
the CAPTURE phase not the BUBBLE phase if we want it to trigger when
the Next button in the headerbar (which is outside the
GisLanguagePage) has focus. I learned this by reading the
implementation of mnemonics in GtkLabel and copying it here.
- Rewrite the dialog as a custom widget, which trades one kind of
boilerplate for another.
- Use GtkWindow not GtkDialog which is deprecated in GTK 4.10. Debian
Bookworm has 4.8 but we were not using any of the special
functionality …
=> Reimplement factory dialog

gnome-initial-setup/pages/privacy/gis-privacy-page.c, gnome-initial-setup/pages/privacy/gis-privacy-page.ui
This is the spiritual successor of half of
1617c1e20c16c2dca7abd2401cf357c7d54ff389 (“endless-eula: Add endless eula page”). I believe the setting fits more naturally on the Privacy page, where it can be displayed more prominently; this will also allow more vertical space to read the EULA in the EULA page.
The manual definition of an autocleanup for GisPrivacyPage will be obsolete in GNOME 46, where I have rewritten this file to use G_DEFINE_FINAL_TYPE which includes that boilerplate.
I have kept the strings from the previous implementation. “Help make Endless better for everyone” looks a bit weird next to the location services option on this page, but I would rather keep the wording as-is and then haggle over it separately. (For upstream, it would need to be adjusted anyway to …
=> privacy: Add metrics toggle

gnome-initial-setup/gis-driver.c, gnome-initial-setup/gis-page-util.c, gnome-initial-setup/gis-page-util.h, gnome-initial-setup/pages/language/gis-language-page.c
-----
+ e2f1e865 page-util: Add logic to launch eos-installer
Fairly straightforward. Removed some unnecessary imports and stopped using gtk_dialog_run as in other places, and changed `gis_page_util_run_reformatter` to always return after running into an error.
+ 1a94089c language: Launch eos-installer on eosinstaller images
Also pretty simple.
I haven't tested this very thoroughly at all, but it seems to be working as expected.
=> Add eos-installer patches for GNOME 43

gnome-initial-setup/meson.build, gnome-initial-setup/pages/timezone/gis-timezone-page.c, gnome-initial-setup/pages/timezone/gis-timezone-page.h
Some polish for the timezone page, plus a fix for a downstream change.
The geoclue change is [already upstream](https://gitlab.gnome.org/GNOME/gnome-initial-setup/-/commit/06544c44fd12d57a1b05c13987cd9abe178eb3cf). The `G_DECLARE_FINAL_TYPE` and checked-cast changes are sitting on [this MR](https://gitlab.gnome.org/GNOME/gnome-initial-setup/-/merge_requests/242) which I will merge if they get a positive review here. They applied with some small conflicts due to downstream changes to this page.
=> Cleanups for timezone page

gnome-initial-setup/pages/live-chooser/gis-live-chooser-page.c
Hide the "Next" button in the Live Chooser page. It appears that the original intent in gis-live-chooser-page.c was for this this button to be hidden. However, `gis_live_chooser_page_constructed` was incorrectly setting the `has-forward` property to FALSE (its default value), instead of setting it to TRUE.
=> fixup! live-chooser: add the Live Chooser page

gnome-initial-setup/gis-assistant.c, gnome-initial-setup/gis-driver.c, gnome-initial-setup/pages/timezone/gis-timezone-page.ui
Currently the GisAssistant widget (which forms the body of the window, excluding the title/headerbar) is wrapped in a GtkScrolledWindow to support the small-screen case. However since the GTK 4 port, all but one page has its own internal scrolled window. Add one to that one page (timezone) and remove the toplevel one.
This is a precursor to using a WebKitWebView on a EULA page, which does its own internal scrolling and interacted badly with the outermost GtkScrolledWindow. But it's also desirable cleanup that I will send upstream to myself in due course.
=> Remove top-level scrolled window

gnome-initial-setup/gis-assistant.c, gnome-initial-setup/gis-driver.c, gnome-initial-setup/gnome-initial-setup.c, gnome-initial-setup/pages/endless-eula/endless-eula.gresource.xml, gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.c, gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.h, gnome-initial-setup/pages/endless-eula/gis-endless-eula-page.ui, gnome-initial-setup/pages/endless-eula/gis-endless-eula-viewer.c, gnome-initial-setup/pages/endless-eula/gis-endless-eula-viewer.h, gnome-initial-setup/pages/endless-eula/gis-endless-eula-viewer.ui, gnome-initial-setup/pages/endless-eula/meson.build, gnome-initial-setup/pages/meson.build, gnome-initial-setup/pages/timezone/gis-timezone-page.ui, po/POTFILES.in
This is a single commit stacked on top of:
- #351
(Ignore the lack of translations on the headers, and feast your eyes on the Spanish-language PDF.)
Something is funky about the font sizes in the PDF.js toolbar. It's not very visible here but it's really obvious if you open the dropdown menu. However… it's legible, and not a problem for today.
I think that allowing the PDF to extend to the full width of the window, and giving it more vertical height by moving the metrics toggle to the privacy page, makes a big difference in terms of legibility. I personally find it almost impossible to read the EOS 5.1 terms.
Compared to its predecessor 1617c1e20c16c2dca7abd2401cf357c7d54ff389:
- Eliminate use of Evince library to display PDFs, as it has no GTK 4 …
=> Readd Endless EULA page

gnome-initial-setup/gis-assistant.ui
Title buttons shouldn't appear in Initial Setup.
Part-of: <https://gitlab.gnome.org/GNOME/gnome-initial-setup/-/merge_requests/237>
(cherry picked from commit a918811a92faac87cdc4e3f3a40d3d50159a9fc3)
https://phabricator.endlessm.com/T35320
=> assistant: Set "show-title-buttons" property to false

gnome-initial-setup/gis-factory-dialog.c, gnome-initial-setup/gis-factory-dialog.h, gnome-initial-setup/gis-factory-dialog.ui
This is useful in a factory context to check that two machines have not been incorrectly cloned from a disk image that had already been booted.
I also tweaked the error dialog shown if entering test mode fails, removing a use of a deprecated function in the process.
https://phabricator.endlessm.com/T35570
=> factory dialog: Show machine ID

gnome-initial-setup/pages/privacy/gis-privacy-page.ui
This service has been decommissioned and the privacy policy link is 404.
I have not bothered to remove all the code that handles the link click –
it's useless but harmless, and upstream it's been refactored and is used
elsewhere.
Upstream: https://gitlab.gnome.org/GNOME/gnome-initial-setup/-/issues/214
https://phabricator.endlessm.com/T35587
=> privacy: Remove Mozilla Location Service reference
